apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-node-app-deployment
spec:
  selector:
    matchLabels:
      app: nodeapp
  replicas: 1 # tells deployment to run 1 pods matching the template
  targetNamespace: flux
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: kube-node-app
          image: webfairooz/k8-app:1.0
          ports:
          - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: k8-node-app-service
spec:
  type: NodePort
  targetNamespace: flux
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: nodeapp